### PR TITLE
NETD Logo as SVG

### PR DESCRIPTION
**Pull request by tanneberger**

### CODE REVIEW

**Comment by MarcelCoding** [comment]
That's just an SVG with an inline PNG ...

**Comment by tanneberger** [comment]
I know - but I don't think Photoshop can do better than this.

**Comment by MarcelCoding** [comment]
Then what is the point of this pr?  Just leave it as it is.

**Comment by tanneberger** [comment]
Because this is the proper logo from matthias (with the correct font) and not just a copy

**Pull request merged**
